### ISSUE TITLE
UiApp has been deprecated. Please use HtmlService instead.

### ISSUE THREAD

**Issue by vr00n** [OpenCageData/opencagedata-googlesheets-scripts#2]
Getting this error while running the script on a google sheet.

**Comment by freyfogle** [comment]
Hi, thanks for letting us know. It seems Google has, in their wisdom, changed something. We will have a look.

**Comment by freyfogle** [comment]
ok, this has now been fixed. Thanks again for making us aware. 
As before you can find the docs here:
https://opencagedata.com/tutorials/geocode-in-googledocs
